language: generic 
services:
  - docker

script:
  ./travis_build.sh 
  
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  api_key: $GITHUB_DEPLOY_KEY
  file: $TRAVIS_BUILD_DIR/release/artifacts/*
  on:
    tags: true
