language: generic 
services:
  - docker

env:
  global:
    - ARTIFACT_PATH=$TRAVIS_BUILD_DIR/release/artifacts

script:
  ./docker_build.sh 
  
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  api_key: $GITHUB_DEPLOY_KEY
  file: $HOME/release/artifacts/*
  on:
    tags: true
